/*
 * File name:        ParseTree.java (package veryFastPDF.algorithms.grammars.type2grammars.charty)
 * Author(s):        Leo Woerteler, Lukas König
 * Java version:     8.0 (at generation time)
 * Generation date:  ?
 *
 * (c) This file and the EAS (Easy Agent Simulation) framework containing it
 * is protected by Creative Commons by-nc-sa license. Any altered or
 * further developed versions of this file have to meet the agreements
 * stated by the license conditions. 
 * 
 * In a nutshell
 * -------------
 * You are free:
 * - to Share -- to copy, distribute and transmit the work
 * - to Remix -- to adapt the work
 * 
 * Under the following conditions:
 * - Attribution -- You must attribute the work in the manner specified by the 
 *   author or licensor (but not in any way that suggests that they endorse 
 *   you or your use of the work).
 * - Noncommercial -- You may not use this work for commercial purposes.
 * - Share Alike -- If you alter, transform, or build upon this work, you may 
 *   distribute the resulting work only under the same or a similar license to 
 *   this one. 
 * 
 * + Detailed license conditions (Germany):
 *   http://creativecommons.org/licenses/by-nc-sa/3.0/de/
 * + Detailed license conditions (unported):
 *   http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en
 * 
 * This header must be placed in the beginning of any version of this file.
 */

package veryFastPDF.algorithms.grammars.type2grammars.charty;

import java.util.HashMap;
import java.util.HashSet;

/**
 * Class representing a parse tree generated by the {@link ChartParser}.
 * 
 * @author Leo Woerteler, Lukas König
 */
public final class ParseTree {

    /** Root edge of this tree. */
    private final Edge edge;

    public Edge getEdge() {
        return this.edge;
    }
    
    /**
     * Constructor.
     * 
     * @param e
     *            root edge
     */
    ParseTree(final Edge e) {
        edge = e;
    }

    public static HashMap<Integer, HashSet<String>> sameLevelNodes = new HashMap<>();
    
    public String toString(boolean useIndexForMultiSymbolWords) {
        sameLevelNodes.clear();
        String s = this.edge.toString("", 0, useIndexForMultiSymbolWords);
        
        for (Integer level : sameLevelNodes.keySet()) {
            s += "{rank=same; ";
            for (String node : sameLevelNodes.get(level)) {
                s += node + " ";
            }
            s += "};\n";
        }
        
        return s;
    }

    public EdgeListList getDerivation() {
        EdgeListList list = new EdgeListList();
        EdgeList initialEdgeList = new EdgeList(0);
        this.edge.setMarkedL(true);
        initialEdgeList.add(this.edge);
        list.add(initialEdgeList);
        return this.edge.getDerivation(list);
    }
}
