/*
 * File name:        StateInputSymbolPair.java (package eas.fundamentalAlgorithms.turingMachine)
 * Author(s):        Lukas König
 * Java version:     7.0
 * Generation date:  04.12.2013 (17:01:19)
 *
 * (c) This file and the EAS (Easy Agent Simulation) framework containing it
 * is protected by Creative Commons by-nc-sa license. Any altered or
 * further developed versions of this file have to meet the agreements
 * stated by the license conditions. 
 * 
 * In a nutshell
 * -------------
 * You are free:
 * - to Share -- to copy, distribute and transmit the work
 * - to Remix -- to adapt the work
 * 
 * Under the following conditions:
 * - Attribution -- You must attribute the work in the manner specified by the 
 *   author or licensor (but not in any way that suggests that they endorse 
 *   you or your use of the work).
 * - Noncommercial -- You may not use this work for commercial purposes.
 * - Share Alike -- If you alter, transform, or build upon this work, you may 
 *   distribute the resulting work only under the same or a similar license to 
 *   this one. 
 * 
 * + Detailed license conditions (Germany):
 *   http://creativecommons.org/licenses/by-nc-sa/3.0/de/
 * + Detailed license conditions (unported):
 *   http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en
 * 
 * This header must be placed in the beginning of any version of this file.
 */

package veryFastPDF.algorithms.turing;


/**
 * @author Lukas König
 */
public class StateTapeSymbolPair {
    protected String state;
    protected String tapeSymbol;
    private Turing utm;

    public StateTapeSymbolPair(String state, String tapeSymbol, Turing father) {
        super();
        this.state = state;
        this.tapeSymbol = tapeSymbol;
        this.utm = father;
    }

    // These methods can be auto-generated by Eclipse.
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime
                * result
                + ((this.tapeSymbol == null) ? 0 : this.tapeSymbol
                        .hashCode());
        return result;
    }

    // These methods can be auto-generated by Eclipse.
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        StateTapeSymbolPair other = (StateTapeSymbolPair) obj;
        if (this.state == null) {
            if (other.state != null)
                return false;
        } else if (!this.state.equals(other.state))
            return false;
        if (this.tapeSymbol == null) {
            if (other.tapeSymbol != null)
                return false;
        } else if (!this.tapeSymbol.equals(other.tapeSymbol))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "" + utm.convertStateLatex(this.state) + ", " + utm.convertTapeSymbolLatex(this.tapeSymbol) + "";
    }
}
