CREATE DATABASE IF NOT EXISTS xwizard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE xwizard;

CREATE TABLE IF NOT EXISTS SCRIPTS (
  scriptID INT NOT NULL AUTO_INCREMENT,
  script MEDIUMTEXT,
  webFree BOOLEAN DEFAULT FALSE,
  svgCached MEDIUMTEXT,
  pdfCached MEDIUMTEXT,
  PRIMARY KEY (scriptID)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SESSION_DATA (
  sessionID INT NOT NULL AUTO_INCREMENT,
  scriptID INT,
  sourceScriptID INT,
  targetScriptID INT,
  sourceType VARCHAR(50),
  sourceHTMLMethod VARCHAR(50),
  userInformation VARCHAR(500),
  browserName VARCHAR(20),
  mobileAccess BOOLEAN,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  calcDurationMS INT,
  inDebugMode BOOLEAN,
  cookieUserName BIGINT DEFAULT 0,
  language VARCHAR(3) DEFAULT NULL,
  scriptType VARCHAR(40) DEFAULT NULL,
  exercise BOOLEAN DEFAULT NULL,
  exerciseSolved BOOLEAN DEFAULT NULL,
  sulution VARCHAR(50) DEFAULT NULL,
  encrypted BOOLEAN DEFAULT NULL,
  fromIDretrieved VARCHAR(20) DEFAULT NULL,
  errorCode INT(2) DEFAULT 0,
  xwizardVersion VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (sessionID)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CONVERSION_METHODS (
  ID INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8mb4;
