/*
 * File name:        PDFProcessor.java (package eas.math.fundamentalAlgorithms.graphBased)
 * Author(s):        Lukas König
 * Java version:     8.0 (at generation time)
 * Generation date:  13.10.2014 (11:26:10)
 *
 * (c) This file and the EAS (Easy Agent Simulation) framework containing it
 * is protected by Creative Commons by-nc-sa license. Any altered or
 * further developed versions of this file have to meet the agreements
 * stated by the license conditions. 
 * 
 * In a nutshell
 * -------------
 * You are free:
 * - to Share -- to copy, distribute and transmit the work
 * - to Remix -- to adapt the work
 * 
 * Under the following conditions:
 * - Attribution -- You must attribute the work in the manner specified by the 
 *   author or licensor (but not in any way that suggests that they endorse 
 *   you or your use of the work).
 * - Noncommercial -- You may not use this work for commercial purposes.
 * - Share Alike -- If you alter, transform, or build upon this work, you may 
 *   distribute the resulting work only under the same or a similar license to 
 *   this one. 
 * 
 * + Detailed license conditions (Germany):
 *   http://creativecommons.org/licenses/by-nc-sa/3.0/de/
 * + Detailed license conditions (unported):
 *   http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en
 * 
 * This header must be placed in the beginning of any version of this file.
 */

package veryFastPDF.pdfProcessors;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

import eas.miscellaneous.convenience.ExternalFilePathsManager;
import eas.veryFastPDF.MainLink;
import mainServlet.WebLink;
import veryFastPDF.script.RepresentableAsPDF;
import veryFastPDF.script.RepresentableDefault;
import veryFastPDF.web.ConvenienceMethods;

/**
 * @author Lukas König
 */
public abstract class PDFProcessor {
    
    private static final boolean DBLCLICK_RESTARTS_ANIMATION = false;

    public abstract void storeAsPDF(final String fileName, String workingDir);
    public abstract String getSVGCode(final String fileName, String workingDir, String script, int hash) throws UnsupportedOutputFormatException;
    public abstract String getSourceString();
    public abstract String getPreparedSourceString();
    public abstract String getCodePrefix();
    public abstract void addln(String s);
    public abstract int getCodeSizeToBeConsideredLarge();
    public abstract String safetyCodeInCaseOfLargeCodeOrLongOperation(int codeSize);
    public abstract Class<? extends RepresentableAsPDF> getPlainRepresentableClass();

    private RepresentableAsPDF myRep;
    private RepresentableDefault myRepDefault;
    private HashMap<Integer, ArrayList<String>> animationMap = new HashMap<>();
    
    public RepresentableAsPDF getMyRep() {
        return myRep;
    }
    
    public PDFProcessor(RepresentableAsPDF rep) {
        this.myRep = rep;
        try {
            this.myRepDefault = (RepresentableDefault) this.myRep;
        } catch (Exception e) {
        }
        
        if (this.myRepDefault != null) {
            this.animationMap = this.myRepDefault.getAnimate();
        } else {
            ArrayList<String> animateThis = new ArrayList<>();
            animateThis.add(RepresentableDefault.THIS_NAME);
            animateThis.add("");
            this.animationMap.put(0, animateThis);
        }
    }
    
    public final String getPlainPDFScript() {
        return this.getCodePrefix() + "\n" + this.getSourceString();
    }
    
    private HashMap<String, PDFProcessor> preprocessors = new HashMap<>();
    
    /**
     * This method is (currently - Jan. 2016) being replaced by in-script preprocessors.
     * The functionality of this method will remain active, but be aware that using it
     * will lead to scripts that</BR>
     * </BR>
     * (1) are not transferable if converted to the plain PDF string (as the 
     *     PDF files generated by preprocessors have to be available) and</BR>
     *     </BR>
     * (2) are not completely modifiable for the same reason (i.e., if
     *     a graphviz graph is generated by a preprocessor as part of a Latex script, 
     *     there is no way to access the graphviz code, as there is only the file
     *     name in the Latex script).
     * The new way to use preprocessors is now via the preprocessor variables in the
     * script or the Latex subscript mechanism using this notation: "@{}@".
     * 
     * @param fileName   The file name to store the PDF in.
     * @param processor  The processor to generate the file.
     */
    @Deprecated
    public void addPreprocessor(String fileName, PDFProcessor processor) {
        this.preprocessors.put(fileName, processor);
    }
    
    @Deprecated
    public void applyPreprocessors(String tempDir) {
        for (String preprocessorFileName : this.preprocessors.keySet()) {
            this.preprocessors.get(preprocessorFileName).storeAsPDF(
                    WebLink.fileName(preprocessorFileName), tempDir);
        }
    }
    
    public static void createSVGFromPDF_UsingPDF2SVG(String filePathWithoutExtension) {
        File pdf2svgPath;
        if (MainLink.isApplicationOriginDesktop()) { // Desktop mode.
            pdf2svgPath = ExternalFilePathsManager.retrieveExternalFilePath(
                    LaTeXPDF.PATH_TO_PDF2SVG_ID, 
                    true,
                    "Choose the executable file of the pdf2svg program used to convert PDFs into SVGs (usually pdf2svg.exe).",
                    LaTeXPDF.estimator_pdf2svg,
                    WebLink.CONF_FILE,
                    WebLink.pathPDF2SVG_POS);
        } else { // Web mode.
            pdf2svgPath = new File(WebLink.getPDF2SVGPath());
        }

        String[] command = {
            pdf2svgPath.getPath(),
            filePathWithoutExtension + ".pdf",
            filePathWithoutExtension + ".svg"
        };

        ConvenienceMethods.execCommand(command, true);
    }
    
    /*
     * inkscape --without-gui --file=input.pdf --export-plain-svg=output.svg 
     */
    @SuppressWarnings("unused")
    private static void createSVGFromPDF(String filePathWithoutExtension) {
        String command = "\"" + new File(WebLink.getInkscapePath()).getPath() // Note the " which are required on server only.
                + "\" --without-gui "
                + "--file=\"" + filePathWithoutExtension + ".pdf\" " 
                + "--export-plain-svg=\"" + filePathWithoutExtension + ".svg\"";
        
        ConvenienceMethods.execCommand(command, true, false);
    }

    /**
     * Creates an SVG with possible animations.
     * 
     * @param path               Path to store SVG.
     * @param onlyIfNotOnlyThis  Only create SVG if something else than
     *                           this has to be created.
     * @param hash               A hash of this run, allowing to specify 
     *                           unique SVG variables among different frames.
     * 
     * @return  Iff something else was created other than this in case 
     *          onlyIfNotOnlyThis was set to true.
     */
    public boolean createSVGFileFromAnimationInstructions(String path, boolean onlyIfNotOnlyThis, int hash) {
        if (hash < 0) {
            throw new RuntimeException("Hash has to be positive (given " + hash + ").");
        }
        
        float[] viewbox = new float[] {0, 0, 0, 0};

        if (onlyIfNotOnlyThis 
                && this.animationMap.size() == 1
                && this.animationMap.get(0).get(0).equals(RepresentableDefault.THIS_NAME)) {
                return false;
        }
        
        LinkedList<String> allOfIt = new LinkedList<>();
        LinkedList<String> animationLines = new LinkedList<>();
        boolean first = true;
        int countSuccessfulAnims = 0;
        
        for (int count = 0; count < this.animationMap.size(); count++) {
            ArrayList<String> animObj = this.animationMap.get(count);
            ArrayList<String> animObjNext = this.animationMap.get(count + 1);
            ArrayList<String> animObjFirst = this.animationMap.get(0);
            if (animObjNext == null) {
                animObjNext = animObjFirst;
            }
            
            createSVGFromPDF_UsingPDF2SVG(path + WebLink.fileName(animObj.get(0)));
            
            try {
                List<String> lines = Files.readAllLines(Paths.get(path + WebLink.fileName(animObj.get(0)) + ".svg"), StandardCharsets.UTF_8);
                String display = " display=\"none\"";
                
                if (first) {
                    first = false;
                    display = "";
                }
                
                String svgHeader = lines.stream().filter(l -> l.contains("viewBox")).findFirst().orElse("");
                viewbox = extendViewboxPart(svgHeader, viewbox);
                
                lines.remove(0);
                lines.remove(0);
                lines.remove(lines.size() - 1);

                ArrayList<String> linesProcessed = replacePotentialDoubleVars(animObj, lines, hash);
                
                allOfIt.add("<g id=\"" + animObj.get(0) + hash + "\"" + display + ">");
                allOfIt.addAll(linesProcessed);
                allOfIt.add("</g>");
          
                animationLines.add("<set xlink:href=\"#" + animObjNext.get(0) + hash + "\" attributeType=\"XML\" attributeName=\"display\" to=\"block\" begin=\"" + animObj.get(0) + hash + ".click\"/>");
                animationLines.add("<set xlink:href=\"#" + animObj.get(0) + hash + "\" attributeType=\"XML\" attributeName=\"display\" to=\"none\" begin=\"" + animObj.get(0) + hash + ".click\"/>");

                if (DBLCLICK_RESTARTS_ANIMATION) {
                    animationLines.add("<set xlink:href=\"#" + animObjNext.get(0) + hash + "\" attributeType=\"XML\" attributeName=\"display\" to=\"none\" begin=\"" + animObj.get(0) + hash + ".dblclick\"/>");
                    animationLines.add("<set xlink:href=\"#" + animObjFirst.get(0) + hash + "\" attributeType=\"XML\" attributeName=\"display\" to=\"block\" begin=\"" + animObj.get(0) + hash + ".dblclick\"/>");
                }
                
                countSuccessfulAnims++;
            } catch (IOException e) {
                e.printStackTrace();
            }        
        }

        String dimsString = viewbox[0] + " " +
                viewbox[1] + " " + 
                viewbox[2] + " " + 
                viewbox[3];
        
        allOfIt.addFirst("<svg width=\"99%\" height=\"99%\""
                + " viewBox=\"" + dimsString + "\""
                + " xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">");

        if (countSuccessfulAnims > 1) {
            allOfIt.add("<g id=\"animateInstruction" + hash + "\">"
                    + "<text preserveAspectRatio=\"xMaxYMin meet\" style=\"fill:#0000ff;\" x=\"0\" y=\"35\" font-family=\"Verdana\" font-size=\"35\" transform=\"rotate(30 20,270)\">" 
                    + "Click to animate!"
                    + "</text>"
                    + "</g>");
        
            animationLines.add("<animate xlink:href=\"#animateInstruction" + hash + "\" attributeName=\"opacity\" from=\"100\" to=\"0\" dur=\"1.00s\"  begin=\"2s\" id=\"anim1\"/>");
            animationLines.add("<set xlink:href=\"#animateInstruction" + hash + "\" attributeType=\"XML\" attributeName=\"display\" to=\"none\" begin=\"3s\"/>");
            allOfIt.addAll(animationLines);
        }
        
        allOfIt.add("</svg>");
        
        try {
            Files.write(Paths.get(path + WebLink.fileName(RepresentableDefault.THIS_NAME) + ".svg"), allOfIt, StandardCharsets.UTF_8);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        return true;
    }
    /**
     * Replaces some common names in the SVG by a more specific identifier to 
     * be unique both in different animation frames and for different objects
     * on the same HTML page (retrieved via web service).
     * 
     * @param animObj  The names of the animation frames.
     * @param lines    The original lines.
     * @return  The replaced lines.
     */
    private ArrayList<String> replacePotentialDoubleVars(ArrayList<String> animObj, List<String> lines, int hash) {
        ArrayList<String> linesProcessed = new ArrayList<>(lines.size());
        for (String line : lines) {
            String lineProcessed = adjustVarName(
                    animObj, 
                    line,
                    hash,
                    "glyph",
                    "surface",
                    "clip");
            lineProcessed = lineProcessed.replace("clip" + animObj.get(0) + hash + "Path", "clipPath"); // Restore wrongly replaced elements.
            linesProcessed.add(lineProcessed);
        }
        return linesProcessed;
    }

    public String adjustVarName(ArrayList<String> animObj, String line, int hash, String... varNames) {
        String replace = line;
        for (String s : varNames) {
            replace = replace.replace(s, s + animObj.get(0) + hash);
        }
        return replace;
    }

    private float[] extendViewboxPart(String string, float[] oldBox) {
        int pos1 = string.indexOf("viewBox");
        if (pos1 < 0) return oldBox;
        pos1 = string.indexOf("\"", pos1 + 1);
        if (pos1 < 0) return oldBox;
        int pos2 = string.indexOf("\"", pos1 + 1);
        if (pos2 < 0) return oldBox;
        String viewBox = string.substring(pos1 + 1, pos2);
        String[] vbVals = viewBox.split(" ");
        float[] newBox = new float[4];
        
        newBox[0] = Float.parseFloat(vbVals[0]);
        newBox[1] = Float.parseFloat(vbVals[1]);
        newBox[2] = Float.parseFloat(vbVals[2]);
        newBox[3] = Float.parseFloat(vbVals[3]);
        
        newBox[0] = Math.min(newBox[0], oldBox[0]);
        newBox[1] = Math.min(newBox[1], oldBox[1]);
        newBox[2] = Math.max(newBox[2], oldBox[2]);
        newBox[3] = Math.max(newBox[3], oldBox[3]);
        
        return newBox;
    }
}
