-- Textbook example scripts (dasinfobuch.de/skripte.html, the "DAR" templates).
--
-- The 2016 archive only contains scriptIDs up to 15670, so the 25 textbook
-- scripts with higher IDs are missing. This file restores exactly those 25 so
-- that every ID referenced by the textbook resolves via ?template=ID-XXXX.
--
-- The 9 textbook scripts already present in the archive (3761-3766, 3772, 3773,
-- 7439) are deliberately NOT touched here.
--
-- Format matches the SCRIPTS table: CRLF line endings, webFree = 1 (required for
-- public template access). INSERT IGNORE keeps this idempotent and prevents it
-- from overwriting rows a newer dump might already provide.

USE `xwizard`;

INSERT IGNORE INTO `SCRIPTS` (`scriptID`, `script`, `webFree`) VALUES
(15728, 'grammar:\r\nS => T, a | U, b;\r\nT => a, T, a | b, T | T, b | a;\r\nU => b, U, b | a, U | U, a | b;\r\n--declarations--\r\nN=S,T,U;\r\nT=a,b;\r\nS=S;\r\nmultiLetterSymbolsHaveIndex=true;\r\nmaxdepth=10;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=5\r\n--declarations-end--', 1),
(15731, 'grammar:\r\nA(1) => a;\r\nA(2) => A(4), A(7);\r\nA(3) => A(1), A(6);\r\nA(4) => b;\r\nA(5) => A(6), A(1) | A(7), A(4);\r\nA(6) => a | A(3), A(1) | A(4), A(6) | A(6), A(4);\r\nA(7) => b | A(1), A(7) | A(2), A(4) | A(7), A(1);\r\n--declarations--\r\nN=A(1),A(2),A(3),A(4),A(5),A(6),A(7),B(6),B(7);\r\nT=a,b;\r\nS=A(5);\r\ndisplayMode=1;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1),
(15733, 'grammar:\r\nA(1) => a;\r\nA(4) => b;\r\nA(5) => A(6), A(1) | A(7), A(4);\r\nA(6) => a | a, B(6) | b, A(6) | a, A(6), A(1) | b, A(6), B(6) | a, A(6), A(1), B(6);\r\nA(7) => b | a, A(7) | b, B(7) | a, A(7), B(7) | b, A(7), A(4) | b, A(7), A(4), B(7);\r\nB(6) => A(4) | A(4), B(6);\r\nB(7) => A(1) | A(1), B(7);\r\n--declarations--\r\nN=A(1),A(2),A(3),A(4),A(5),A(6),A(7),B(6),B(7);\r\nT=a,b;\r\nS=A(5);\r\ndisplayMode=1;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1),
(15741, 'grammar:\r\nA(1) => a;\r\nA(4) => b;\r\nA(5) => a, A(1) | b, A(4) | a, A(7), A(4) | a, B(6), A(1) | b, B(7), A(4) | b, A(6), A(1) | a, A(6), A(1), A(1) | a, A(7), B(7), A(4) | b, A(7), A(4), A(4) | b, A(6), B(6), A(1) | a, A(6), A(1), B(6), A(1) | b, A(7), A(4), B(7), A(4);\r\nA(6) => a | a, B(6) | b, A(6) | a, A(6), A(1) | b, A(6), B(6) | a, A(6), A(1), B(6);\r\nA(7) => b | a, A(7) | b, B(7) | a, A(7), B(7) | b, A(7), A(4) | b, A(7), A(4), B(7);\r\nB(6) => A(4) | A(4), B(6);\r\nB(7) => A(1) | A(1), B(7);\r\n--declarations--\r\nN=A(1),A(2),A(3),A(4),A(5),A(6),A(7),B(6),B(7);\r\nT=a,b;\r\nS=A(5);\r\ndisplayMode=1;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1),
(15742, 'grammar:\r\nA(1) => a; A(4) => b;\r\nA(5) => a, A(1) | b, A(4) | a, A(7), A(4) | a, B(6), A(1) | b, B(7), A(4) | b, A(6), A(1) | a, A(6), A(1), A(1) | a, A(7), B(7), A(4) | b, A(7), A(4), A(4) | b, A(6), B(6), A(1) | a, A(6), A(1), B(6), A(1) | b, A(7), A(4), B(7), A(4);\r\nA(6) => a | a, B(6) | b, A(6) | a, A(6), A(1) | b, A(6), B(6) | a, A(6), A(1), B(6);\r\nA(7) => b | a, A(7) | b, B(7) | a, A(7), B(7) | b, A(7), A(4) | b, A(7), A(4), B(7);\r\nB(6) => b | b, B(6); B(7) => a | a, B(7);\r\n--declarations--\r\nN=A(1),A(2),A(3),A(4),A(5),A(6),A(7),B(6),B(7);\r\nT=a,b; S=A(5);\r\ndisplayMode=1;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1),
(16336, 'grammar:\r\nS => X | XkaX, S, u, S, XkzX | XkaX, S, o, S, XkzX | S, u, S | S, o, S | n, S;\r\nX => x1 | x2 | x3;\r\n--declarations--\r\nN=S,X;\r\nT=x1,x2,x3,u,o,n,XkaX,XkzX;\r\nS=S;\r\ndisplayMode=1;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1),
(16356, 'grammar parse(dies, ist, ein, Beispiel, zur, Bedienung, des, XWizards)--0:\r\nX => Bedienung | Beispiel | XWizards | des | dies | ein | ist | zur | X, X;\r\n--declarations--\r\nN=X;\r\nT=Bedienung, Beispiel, XWizards, des, dies, ein, ist, zur;\r\nS=X;\r\ndisplayMode=2;\r\nmultiLetterSymbolsHaveIndex=false;\r\nparseTreeNum=0\r\n--declarations-end--', 1),
(16364, 'pda:\r\n(s0, a, k) => (s1, k);\r\n(s0, b, k) => (s2, k);\r\n(s1, a, k) | (s2, b, k) | (sf1, a, k) | (sf2, b, k) => (s0, k);\r\n(s1, b, k) | (s2, a, k) | (sf1, b, k) | (sf2, a, k) => (s3, k);\r\n(s3, a, k) => (sf2, k);\r\n(s3, b, k) => (sf1, k);\r\n--declarations--\r\ns0=s0;\r\nF=s0,sf1,sf2;\r\nkSymb=k;\r\ninputs=bbbabba;\r\nsimSteps=0;\r\ndisplayMode=0\r\n--declarations-end--', 1),
(16373, 'fsm:\r\n(s0, a) | (s1, a) | (s4, b) => s1;\r\n(s0, b) => s4;\r\n(s1, b) | (s2, b) | (s4, a) => s3;\r\n(s2, a) | (s3, a) | (s3, b) => s2;\r\n--declarations--\r\nsimulateToStep=-1;\r\ninput=null;\r\ns0=s0;\r\nF=s3,s0,s1,s2;\r\ndisplayMode=1;\r\nshowMinimizedFSM=true;\r\nshowDeterministicFSM=true\r\n--declarations-end--', 1),
(16377, 'pda:\r\n(s1, [, [) => (s1, [[);\r\n(s1, lambda, k) => (s0, k);\r\n(s0, [, k) => (s1, [k);\r\n(s1, ], [) => (s1, lambda);\r\n--declarations--\r\ns0=s0;\r\nF=s0;\r\nkSymb=k;\r\ninputs=[][[]];\r\nsimSteps=0\r\n--declarations-end--', 1),
(16379, 'pda:\r\n(s0, 0, 0) => (s0, 00);\r\n(s0, 0, 1) => (s0, 01);\r\n(s0, 0, k) => (s0, 0k);\r\n(s0, 1, 0) => (s0, 10);\r\n(s0, 1, 1) => (s0, 11);\r\n(s0, 1, k) => (s0, 1k);\r\n(s0, M, 0) => (s1, 0);\r\n(s0, M, 1) => (s1, 1);\r\n(s0, M, k) | (s1, lambda, k) => (se, k);\r\n(s1, 0, 0) | (s1, 1, 1) => (s1, lambda);\r\n--declarations--\r\ns0=s0;\r\nF=se;\r\nkSymb=k;\r\ninputs=101101M101101;\r\nsimSteps=0;\r\ndisplayMode=0\r\n--declarations-end--', 1),
(16380, 'pda:\r\n(s0, a, A) => (s1, B);\r\n(s0, a, E) | (s0, b, F) | (s1, a, B) | (s1, b, C) => (s0, A);\r\n(s0, a, F) | (s0, b, E) | (s1, a, C) | (s1, b, B) => (s1, D);\r\n(s0, b, A) => (s1, C);\r\n(s0, lambda, k) => (s0, Ak);\r\n(s1, a, D) => (s0, F);\r\n(s1, b, D) => (s0, E);\r\n--declarations--\r\ns0=s0;\r\nF=s0;\r\nkSymb=k;\r\ninputs=bbbabba;\r\nsimSteps=0;\r\ndisplayMode=0\r\n--declarations-end--', 1),
(16416, 'fsm:\r\n(s0, a) | (s1b, a) | (s2b, a) => s1a;\r\n(s0, b) | (s1a, b) | (s2a, b) => s1b;\r\n(s1a, a) => s2a;\r\n(s1b, b) => s2b;\r\n(s2a, a) | (s2b, b) | (s3, a) | (s3, b) => s3;\r\n--declarations--\r\nsimulateToStep=-1;\r\ninput=null;\r\ns0=s0;\r\nF=s3;\r\ndisplayMode=0;\r\nshowMinimizedFSM=false;\r\nshowDeterministicFSM=false\r\n--declarations-end--', 1),
(16456, 'pda:\r\n(s0, 0, 0) => (s0, 00);\r\n(s0, 0, 1) => (s0, 01);\r\n(s0, 0, k) => (s0, 0k);\r\n(s0, 1, 0) => (s0, 10);\r\n(s0, 1, 1) => (s0, 11);\r\n(s0, 1, k) => (s0, 1k);\r\n(s0, lambda, 0) => (s1, lambda) | (s1, 0);\r\n(s0, lambda, 1) => (s1, lambda) | (s1, 1);\r\n(s0, lambda, k) => (s1, k);\r\n(s1, 0, 0) | (s1, 1, 1) => (s1, lambda);\r\n(s1, lambda, k) => (se, k);\r\n--declarations--\r\ns0=s0;\r\nF=se;\r\nkSymb=k;\r\ninputs=1001;\r\nsimSteps=-1;\r\nmaxNondetCalcDepth=18;\r\ndisplayMode=0\r\n--declarations-end--', 1),
(16463, 'fsm:\r\n(s0, a) => s3; (s0, b) => s0 | s6;\r\n(s1, a) | (s4, a) => s5;\r\n(s1, b) => s5 | s2 | s0;\r\n(s2, a) => s1; (s2, b) => s2 | s4;\r\n(s3, a) => s4 | s1 | s6;\r\n(s4, b) => s4 | s1;\r\n(s5, a) => s6 | s4; (s5, b) => s6;\r\n(s6, a) | (s6, b) => s4;\r\n--declarations--\r\nsimulateToStep=0;\r\ninput=babaabbb;\r\ns0=s0;\r\nF=s0,s2;\r\ndisplayMode=0;\r\nshowMinimizedFSM=false;\r\nshowDeterministicFSM=false\r\n--declarations-end--', 1),
(16496, 'grammar:\r\nS => T, a | U, b | epsilon;\r\nA => a;\r\nB => b;\r\nT => A, A, T | B, T | A;\r\nU => B, B, U | A, U | B;\r\nA, B => B, A;\r\nB, A => A, B;\r\n--declarations--\r\nN=A,B,C,D,E,S,T,U;\r\nT=a,b,c,d;\r\nS=S;\r\nmaxdepth=7;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=100\r\n--declarations-end--', 1),
(16562, 'grammar:\r\nS => T, a /*| U, b*/ | epsilon;\r\nA => a; B => b;\r\nT => A, A, T | B, T | A;\r\nU => B, B, U | A, U | B;\r\nA, B => C, B; A, F => A, B;\r\nB, A => E, A; B, D => B, A;\r\nC, B => C, D; C, D => B, D;\r\nE, A => E, F; E, F => A, F;\r\n--declarations--\r\nN=A,B,C,D,E,F,S,T,U;\r\nT=a,b,c,d;\r\nS=S;\r\nmultiLetterSymbolsHaveIndex=false;\r\nmaxdepth=9;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=100\r\n--declarations-end--', 1),
(16563, 'grammar:\r\nS => T, a /*| U, b*/ | epsilon;\r\nT => a, T, a | b, T | T, b | a;\r\nU => b, U, b | a, U | U, a | b;\r\n--declarations--\r\nN=S,T,U;\r\nT=a,b;\r\nS=S;\r\nmultiLetterSymbolsHaveIndex=true;\r\nmaxdepth=10;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=5\r\n--declarations-end--', 1),
(16727, 'grammar parse(a,b,b,b,a,a,b,a,b,b)--0:\r\nS => epsilon | T, a | U, b;\r\nT => a | T, b | b, T | a, T, a;\r\nU => b | U, a | a, U | b, U, b;\r\n--declarations--\r\nN=S,T,U;\r\nT=a,b;\r\nS=S;\r\ndisplayMode=0;\r\nmaxdepth=10;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=5;\r\nmultiLetterSymbolsHaveIndex=true;\r\nparseTreeNum=0\r\n--declarations-end--', 1),
(16778, 'grammar:\r\nC, B => B, C;\r\nS\' => S | epsilon;\r\nS => a, S, B, C | a, B, C;\r\na, B => a, b;\r\nb, B => b, b;\r\nb, C => b, c;\r\nc, C => c, c;\r\n--declarations--\r\nN=S,S\',B,C,A;\r\nT=a,b,c;\r\nS=S\';\r\ndisplayMode=0;\r\nmaxdepth=90;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=9;\r\nmultiLetterSymbolsHaveIndex=false;\r\nparseTreeNum=0\r\n--declarations-end--', 1),
(16824, 'fsm:\r\n(S, a) => A1 | B0;\r\n(S, b) => A0 | B1;\r\n(A0, a) | (A1, b) => A1;\r\n(A0, b) => A0;\r\n(A1, a) => A0 | s5;\r\n(B0, a) => B0;\r\n(B0, b) | (B1, a) => B1;\r\n(B1, b) => B0 | s5;\r\n--declarations--\r\ns0=S;\r\nF=s5\r\n--declarations-end--', 1),
(16836, 'grammar:\r\nA0 => a, A1 | b, A0;\r\nA1 => a | a, A0 | b, A1;\r\nB0 => b, B1 | a, B0;\r\nB1 => b | b, B0 | a, B1;\r\nS => a, A1 | b, A0 | b, B1 | a, B0 | epsilon;\r\n--declarations--\r\nN=S,A0,A1,B0,B1;\r\nT=a,b,c;\r\nS=S;\r\ndisplayMode=0;\r\nmaxdepth=100;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=4;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1),
(16837, 'grammar parse(a, b, b, a, a, a)--0:\r\nA0 => a, A1 | b, A0;\r\nA1 => a | a, A0 | b, A1;\r\nB0 => b, B1 | a, B0;\r\nB1 => b | b, B0 | a, B1;\r\nS => a, A1 | b, A0 | b, B1 | a, B0 | epsilon;\r\n--declarations--\r\nN=S,A0,A1,B0,B1;\r\nT=a,b,c;\r\nS=S;\r\ndisplayMode=0;\r\nmaxdepth=100;\r\ncutNonTerminalBranches=true;\r\ncutTerminalDoubleBranches=true;\r\nmaxLengthWords=4;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1),
(17177, 'grammar parse(a,b,a,b,b,a,b)--0:\r\nA(1) => a; A(4) => b;\r\nA(5) => a, A(1) | b, A(4) | a, A(7), A(4) | a, B(6), A(1) | b, B(7), A(4) | b, A(6), A(1) | a, A(6), A(1), A(1) | a, A(7), B(7), A(4) | b, A(7), A(4), A(4) | b, A(6), B(6), A(1) | a, A(6), A(1), B(6), A(1) | b, A(7), A(4), B(7), A(4);\r\nA(6) => a | a, B(6) | b, A(6) | a, A(6), A(1) | b, A(6), B(6) | a, A(6), A(1), B(6);\r\nA(7) => b | a, A(7) | b, B(7) | a, A(7), B(7) | b, A(7), A(4) | b, A(7), A(4), B(7);\r\nB(6) => b | b, B(6); B(7) => a | a, B(7);\r\n--declarations--\r\nN=A(1),A(4),A(5),A(6),A(7),B(6),B(7);\r\nT=a,b; S=A(5);\r\ndisplayMode=0;\r\nmultiLetterSymbolsHaveIndex=true;\r\nparseTreeNum=0\r\n--declarations-end--', 1),
(17493, 'grammar parse(a,b,a,b,b,a,b)--0:\r\nS => T, Ca | U, Cb;\r\nT => a | Cb, T | Ca,D1 | T, Cb;\r\nU => b | Ca, U | Cb,D2 | U, Ca;\r\nCa => a;\r\nCb => b;\r\nD1 => T,Ca;\r\nD2 => U,Cb;\r\n--declarations--\r\nN=Ca,Cb,D1,D2,S,T,U;\r\nT=a,b;\r\nS=S;\r\nmultiLetterSymbolsHaveIndex=true;\r\n--declarations-end--', 1);
